FROM python:3.12-rc-slim-buster 

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    linux-headers-arm64 \ 
    && rm -rf /var/lib/apt/lists/* # Clean up apt cache

COPY requirements.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt 

COPY . .

CMD ["python3", "main.py"] 